# Generated by Django 3.2 on 2021-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
