# Generated by Django 3.2 on 2021-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emails',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
