# Generated by Django 3.2 on 2021-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_user_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emails',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
