# Generated by Django 3.2 on 2021-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_user_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('accountnum', models.CharField(max_length=150, unique=True)),
                ('acctype', models.CharField(max_length=40)),
                ('min_bal', models.FloatField(max_length=150)),
            ],
        ),
    ]
